import React from 'react'

export default function Funcionamento() {
  return (
    <main>
        <section>
            <h1>Horto tech</h1>
            <p>sistema autimotizado de monitoramento
            para cultivo de hortaliças</p>
            <img src="" alt="" />
            <p>O Horta tech funciona na área de Robótica, propõe o desenvolvimento de um sistema automatizado de monitoramento para cultivo de hortaliças, empregando a plataforma Arduino como base. O objetivo principal é conceber uma solução que viabilize o controle eficaz de variáveis fundamentais para o desenvolvimento vigoroso das plantas, incluindo a umidade do solo, a temperatu ra ambiente e a luminosidade.</p>  
        </section>
        
        
        <section>
            <h2>Funcionamento</h2>
            <img src="" alt="" />
            <p>O sistema é composto por sensores integrados ao Arduino que coletam dados em tempo real sobre as condições ambientais da horta. Esses dados são processados e enviados para uma interface gráfica onde o usuário pode monitorar os parâmetros e receber alertas sobre a necessidade de irrigação ou ajustes nas condições de cultivo. Além disso, o sistema pode ser programado para acionar automaticamente a irrigação quando os níveis de umidade do solo estiverem abaixo do ideal.</p>
        </section>
    </main>
  )
}
